channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - pytorch::pytorch=2.4.1
  - pytorch::torchvision
  - pandas
  - numpy>=2.0
  - pyteomics
  - cpuonly
  - tqdm
  - pyarrow
  - pip
  - pip:
    - onnx==1.18.0
    - onnx-ir==0.1.4
    - onnxruntime==1.22.1
    - onnxscript==0.3.2
    - pytest