channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - openpyxl
  - tenacity
  - pip:
    - pandas==2.2.3
    - massql==0.0.15
    - requests
    - python-dotenv
    - PyYAML
    - pymzml
    - pyteomics
    - plotly
    - scikit-learn