channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - openpyxl
  - pip:
    - pandas
    - massql
    - requests
    - python-dotenv
    - PyYAML
    - pymzml
    - pyteomics
    - plotly
    - scikit-learn